export const APP_LABELS = {
  appTitle: 'Preproute Test Management',
  common: {
    edit: 'Edit',
    delete: 'Delete',
    cancel: 'Cancel',
    saveAsDraft: 'Save as Draft',
    saveAndContinue: 'Save & Continue',
    submit: 'Create Test',
    update: 'Update',
    back: 'Back to list',
    active: 'Active',
    topic: 'Topic',
    subTopic: 'Sub-Topic',
    duration: 'Duration',
    difficulty: 'Difficulty',
    testDetails: 'Test Details',
    loading: 'Loading...',
  },
  nav: {
    dashboard: 'Dashboard',
    testCreation: 'Test Creation',
    testTracking: 'Test Tracking',
  },
  login: {
    title: 'Login',
    helper: 'Use your company provided Login credentails',
    userId: 'User ID',
    password: 'Password',
    submit: 'Login',
    forgotPassword: 'Forgot Password?',
    forgotPasswordHint: 'Please contact your administrator to reset your password.',
    forgotPasswordTitle: 'Reset Password',
    forgotPasswordSubmit: 'Send Reset Link',
    forgotPasswordSuccess: 'If an account exists, you will receive a reset link.',
    backToLogin: 'Back to Login',
    errorRequired: 'Please enter both email and password.',
  },
  tests: {
    editTitle: 'Edit Test',
    title: 'Title',
    add: 'Add',
    empty: 'No tests found.',
    view: 'View',
  },
  dashboard: {
    welcome: 'Welcome to Test Management',
    totalTests: 'Total Tests',
    passed: 'Passed',
    failed: 'Failed',
    pending: 'Pending',
    draft: 'Draft',
    createTest: 'Create New Test',
    searchPlaceholder: 'Search by name or subject...',
    filterByStatus: 'Filter by status',
    detailsTitle: 'Test Details',
    name: 'Name',
    subject: 'Subject',
    status: 'Status',
    createdDate: 'Created Date',
    actions: 'Actions',
    close: 'Close',
  },
  testCreation: {
    title: 'Create New Test',
    testName: 'Name of Test',
    subject: 'Subject',
    topic: 'Topic',
    subTopic: 'Sub-Topic',
    duration: 'Duration (minutes)',
    difficulty: 'Test Difficulty Level',
    next: 'Next',
    previous: 'Previous',
    step: 'Step',
    of: 'of',
    placeholderTestName: 'Enter test name',
    placeholderSubject: 'Enter subject',
    placeholderDuration: 'Enter duration in minutes',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    chapterwise: 'Chapterwise',
    pyq: 'PYQ',
    mockTest: 'Mock Test',
    chapterwiseBreadcrumb: 'Chapterwise',
    pyqBreadcrumb: 'PYQ',
    mockTestBreadcrumb: 'Mock Test',
    markingScheme: 'Marking Scheme',
    wrongAnswer: 'Wrong Answer',
    unattempted: 'Unattempted',
    correctAnswer: 'Correct Answer',
    totalQuestions: 'No. of Questions',
    placeholderTotalQuestions: 'Ex. 250marks',
    totalMarks: 'Total Marks',
    chooseFromDropdown: 'Choose from Drop-down',
    details: 'Test Details',
    question: 'Question',
    questionsNav: 'Questions',
    totalLabel: 'Total:',
    options: 'Options',
    option: 'Option',
    optionsCount: 'options',
    description: 'Description',
    placeholderDescription: 'Enter question description...',
    explanation: 'Explanation (optional)',
    placeholderSolution: 'Enter explanation...',
    mediaUrl: 'Media URL (optional)',
    placeholderMediaUrl: 'Enter media URL',
    questionDifficulty: 'Difficulty',
    selectDifficulty: 'Select difficulty',
    deleteOption: 'Delete',
    addOption: 'Add Option',
    addAnotherQuestion: 'Add Another Question',
    mockTestComingSoon: 'Mock Test configuration will be available here.',
    pyqComingSoon: 'PYQ test configuration will be available here.',
    subTopicOptions: ['Sub-Topic 1', 'Sub-Topic 2', 'Sub-Topic 3'],
  },
  testTracking: {
    title: 'Test Tracking',
    empty: 'No tests found.',
    search: 'Search tests...',
  },
  user: {
    logout: 'Logout',
  },
  images: {
    logo: '/preproute.svg',
    dashboardIcon: '/dashboard.svg',
    testCreationIcon: '/create.svg',
    testTrackingIcon: '/track.svg',
    testTubeManImage: '/test-tube-man.svg',
    testSubjectIcon: '/test-subject.svg',
    cognitionIcon: '/cognition.svg',
  },
} as const;

export type AppLabels = typeof APP_LABELS;
